### ISSUE TITLE
Square avatar images do not fill in the contents of the carousel block

### ISSUE THREAD

**Issue by apoapostolov** [death-save/combat-carousel-public#17]
avatar potrait logic needs to be improved as it currently doesn't handle square avatar images well, made via Tokenizer to fit square avatar panels in sheets. It should be fit by height, not fit by width.

**Comment by eclarke12** [comment]
I might have already fixed this in the next alpha, but to be sure, can you please attach a screenshot of the undesirable behaviour and if possible DM me the image used so I can do some testing?
