### ISSUE TITLE
Info updating only on VTT load and start of combat and as player loads in not after every hook, please fix this is irratating to say the least

### ISSUE THREAD

**Issue by Zarhog** [death-save/combat-carousel-public#170]
**Describe the bug**
Combat carosel is not autoupdating information, it only seems to check at the beginning of combat and as a player loads not as information changes, which leads to players having outdated info

**To Reproduce**
CBF

**Expected behavior**
it should update data after every hook to insure that all players have updated info

**Screenshots**
CBF

**Environment Info (please complete the following information):**
![image](https://github.com/death-save/combat-carousel/assets/76391362/170a2ef4-c874-4610-a5bf-b3dc32047072)
browsers = CBF its all
Versioin of foundry V11 313

**Additional context**
CBF should be easy enough to reproduce if you cannot ill provide more info

**Comment by eclarke12** [comment]
Combat Carousel is no longer supported. Please read: https://github.com/death-save
