### ISSUE TITLE
0.1.1 Players able to click on any portrait and affect whose turn it is

### ISSUE THREAD

**Issue by iotech-fvtt** [death-save/combat-carousel-public#19]
With combat started player (TRUSTED) is able to click on any card in the carousel and make it that actor's turn

**To Reproduce**
1. (GM) Select actors, add to tracker, start combat
2. [Player] Click various cards n carousel. Turn changes to selected actor

**Expected behavior**
Players should not be able to affect the turn sequence in this manner. 

**Screenshots**
I have an MP4 of it, but github doesnt allow it

**Desktop (please complete the following information):**
 - OS: Windows 10
 - Browser Edge
 - Version 0.1.1
- Foundry 0.6.6
- Node

**Comment by eclarke12** [comment]
Valid. Missed in fix for #2 . Pooling for v0.1.2
