### ISSUE TITLE
0.1.1 Players unable to roll initiative

### ISSUE THREAD

**Issue by iotech-fvtt** [death-save/combat-carousel-public#20]
**Describe the bug**
When the player clicks the d20 on their card, it doesnt roll initiative, it just makes it their turn. Applies if player owns more than one actor, it switches turn to that actor. GM can still roll initiative with the d20 icon. See Issue #19 

**To Reproduce**
1.Be a player, et your actors added to Carousel
2. Click on the red d20 icon to roll initiative

**Expected behavior**
Initiative should be rolled. It is not.  

**Screenshots**
Video available on request (Github wont let me attach mp4)

**Desktop (please complete the following information):**
 - OS: Win10
 - Browser Edge
 - Version 0.1.1
Foundry 0.6.6
Node

**Comment by eclarke12** [comment]
Regression from fixing #1 . Players should be able to roll initiative unless there is a value present. Pooling for v0.1.2
