### ISSUE TITLE
Can't see all the characters to the left.

### ISSUE THREAD

**Issue by Sunamon** [death-save/combat-carousel-public#34]
**Describe the bug**
Can't scroll all the way to the left. There are several characters to the left of the one shown in the picture.

**To Reproduce**
1. Add a bunch of tokens to the combat
2. advance turns to the last user in the combat tracker
3. Scroll all the way to the left on the combat carousel 
4. you can't see the characters on the left.

**Expected behavior**
should be able to see all the characters left and right

**Screenshots**
![image](https://user-images.githubusercontent.com/65740342/96157444-8bb75880-0ecf-11eb-80e1-495e49ac287c.png)

**Desktop (please complete the following information):**
chrome, 7.4

**Comment by eclarke12** [comment]
validated this. the issue is because splide applies a `translate-x` with a negative value it breaks the scroll bar. need to find a solution
