### ISSUE TITLE
'Docked' Combat Carousel Appears Every Turn

### ISSUE THREAD

**Issue by saneronsds** [death-save/combat-carousel-public#43]
**Description**
When the Combat Carousel is docked (or 'hidden), it will re-appear every time the GM moves to the next turn. This can be problematic for players who hide it to save screen real-estate.

**To Reproduce** 

Be a player.
Hide the Combat Carousel.
(As a GM) Move to the next turn

**Expected behavior** 

When hidden, the combat carousel should remain hidden.

**Desktop (please complete the following information):**

**OS:** Windows
**Browser:** Various (Chromium Browsers mostly: Chrome, Brave, Edge)

**Comment by JonWaterfall** [comment]
This seems to still be an issue in the currect version.
