### ISSUE TITLE
Add size options for Carousel

### ISSUE THREAD

**Issue by yoshisman8** [death-save/combat-carousel-public#48]
**Is your feature request related to a problem? Please describe.**
The combat carrousel takes up a lot of screen real space with no option to shrink it down. This makes playing in relatively small monitors really hard.

**Describe the solution you'd like**
A simple slider or scale field to shrink down the icons on the carousel would be nice.

**Describe alternatives you've considered**
There's no real alternative solution other than not using the carousel.

**Additional context**
![image](https://user-images.githubusercontent.com/4214215/100462175-3d859f80-30a0-11eb-862f-ab1c16187de6.png)
Notice how the carousel and quick drop menu compete for a good portion of the screen space.

**Comment by thadrine** [comment]
Seconded

**Comment by eclarke12** [comment]
https://www.patreon.com/posts/carousel-strikes-46720823
