### ISSUE TITLE
Carousel shows "mystery man" image for all NPCs instead of their token

### ISSUE THREAD

**Issue by BryanOrabutt** [death-save/combat-carousel-public#49]
**Describe the bug**
NPC characters do not get an appropriate image on the carousel. The mystery man icon shows in place even when their token is set to different image.

**To Reproduce**
1. Create an NPC actor and assign a token image
2. Add token to active encounter
3. Observe the image in the carousel is not the same as the token.

**Expected behavior**
The image in the carousel should be the same as the token.

**Screenshots**
![Capture](https://user-images.githubusercontent.com/9027080/100936299-e6743600-34b6-11eb-9d3a-edc9c1097820.PNG)

**Desktop (please complete the following information):**
 - OS: Win10
 - Browser: Running in foundry directly
 - Version 0.7.7

**Comment by BryanOrabutt** [comment]
Fixed by having carousel use `token.img` rather than `token.actor.img`

**Comment by BryanOrabutt** [comment]
Actually seems to be more of an issue with the PF2e system. NPC sheets do not allow to assign an actor image while player character sheets do. Closing this issue. Added a field to the NPC sheet in the PF2e system to allow actor image selection.

**Comment by eclarke12** [comment]
@BryanOrabutt the next version of CC will include the ability to select Actor or  Token images to display
