### ISSUE TITLE
add option do display AC or another fields to each token in the bar.

### ISSUE THREAD

**Issue by kainpen** [death-save/combat-carousel-public#65]
**Is your feature request related to a problem? Please describe.**
This would just be an enhancement to make things easier to look up for GM, with out have to change highlighting creature or target. This would save a lot of time of having to open character sheets and reselect targets. auto application of damage or healing from the chat windows is built in foundry depend on target and what creature is highlighted at the time.  When player may ask for ac of a creature or if their attack hit, you have to open up the creatures sheet to look up the info.  Then you then have to go back and reselect or highlight the targets again.

**Describe the solution you'd like**
It would be great if, I could look up the image for a player or npc/monster on the Icon on the carousel and see a shield with current armor class, Save DC, or some other value that may be important depending on the game system and be able to select several options. I would no longer have to open sheets to look up that info. It would be there already at my finger tips.  Not everyone would necessarily want this and it would have to be customizable, option from the module settings menu.

**Describe alternatives you've considered**
Currently I can use the combat tracker to have see one value of my choice the AC or a single other value off a character sheet. So you have to constantly swap between the chat log or combat tracker to see the info, or you can pop the combat tracker outside of that window, but then that defeat the purpose of the carousel

**Additional context**
Adding image of the idea. Using just text, I think it would look better if some kind of icon was used and the number in it. Like you guys have d20 for the initiative value. 
![idea](https://user-images.githubusercontent.com/85844266/121819343-24b29500-cc52-11eb-8346-ab59aa014c4a.PNG)

**Comment by eclarke12** [comment]
Delivered in CC alpha 2 https://www.patreon.com/posts/46720823
