### ISSUE TITLE
Support for Cyberpunk Red Core Health and other Resources

### ISSUE THREAD

**Issue by jerichojx** [death-save/combat-carousel-public#66]
**Is your feature request related to a problem? Please describe.**

**Describe the solution you'd like**
When using the ruleset for Cyberpunk red Core, the HP as well as other resources do not show up. I would like to track resources for Cyberpunk on the Carousel

**Describe alternatives you've considered**

**Additional context**

**Comment by eclarke12** [comment]
in CC alpha 2 you can set the health attribute used. https://www.patreon.com/posts/carousel-strikes-46720823 coming into public beta soon:tm:
